### ISSUE TITLE
Transformation Build

### ISSUE THREAD

**Issue by goldforg** [graphsense/graphsense-setup#12]
Hey,

I've run into issue by building graphsense-transformation module.

https://github.com/graphsense/graphsense-transformation/blob/master/Dockerfile contains references to the libraries/packages that couldn't be accessible anymore.
>> https://dl.bintray.com/sbt/debian
>> https://www.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-without-hadoop-scala-2.12.tgz

Even by replacing them with command
>> docker run transformation

I get issues something like this:
>> SERVER ERROR: Bad Gateway url=https://dl.bintray.com/spark-packages/maven/org/apache/apache/18/apache-18.jar
>> SERVER ERROR: Bad Gateway url=https://dl.bintray.com/spark-packages/maven/org/apache/commons/commons-parent/41/commons-parent-41.jar
>> SERVER ERROR: Bad Gateway url=https://dl.bintray.com/spark-packages/maven/org/apache/apache/16/apache-16.jar
>> SERVER ERROR: Bad Gateway url=https://dl.bintray.com/spark-packages/maven/org/apache/commons/commons-parent/39/commons-parent-39.jar
>> SERVER ERROR: Bad Gateway url=https://dl.bintray.com/spark-packages/maven/org/sonatype/oss/oss-parent/9/oss-parent-9.jar
>> SERVER ERROR: Bad Gateway url=https://dl.bintray.com/spark-packages/maven/io/netty/netty-parent/4.0.33.Final/netty-parent-4.0.33.Final.jar

Is it possible to take a look on this graphsense-transformation module?

Thanks in advance!

**Comment by defconst** [comment]
Fixed in graphsense/graphsense-transformation@0316272
