### ISSUE TITLE
CPU/RAM/Storage Requirement

### ISSUE THREAD

**Issue by rider8581** [graphsense/graphsense-setup#13]
Good day.

Thank you for your contribution.

I was trying to run the project but couldn't be sure what spec of machine it needs.

To run all components including client, ingest, transformer, rest, and dashboard except graphsense-blocksci, how much cpu, ram, storage should I put?
Now I am running client only and it keeps downloading files and it already gets to 80GB. What size of storage should I put for it?

Kindly guide me please.

Thank you

**Comment by defconst** [comment]
Storage size of clients:
```
454.2 GiB  /btc                                                                        
210.0 GiB /bch
  76.1 GiB /ltc
  35.5 GiB /zec
832.5 Gib openethereum
```
BlockSci ingest needs >= 64GiB RAM.
The Spark Transformation needs a cluster of several machines (out cluster has in total: 2.5 TB RAM and 60 TB SSD storage).

**Comment by rider8581** [comment]
https://beta.graphsense.info/
Could you guide me how I can have API key here for some trial?

**Comment by defconst** [comment]
https://graphsense.info/contact/
