### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by modir** [graphsense/graphsense-setup#4]
In the readme file under "Prerequisites" you have this information:
`standalone Apache Spark cluster (version 2.7.7/Scala 2.12)`

But the latest Spark version in the 2.x series is 2.4.7. Afterwards came version 3.0.0.

So what is the correct version then?

**Comment by dshatz** [comment]
2.4.7 is the version

**Comment by defconst** [comment]
Fixed in bdb015273f1eaf0866419fb1dbb716356e0486ed
